# Generated by Django 5.2.1 on 2025-05-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('subheading', models.CharField(max_length=300)),
                ('tldr', models.TextField()),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('estimated_read_time', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
