# Generated by Django 5.2.1 on 2025-05-21 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.blogpost'),
            preserve_default=False,
        ),
    ]
